<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<!--<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>-->
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\dist\Entities\**" />
    <Content Remove="wwwroot\dist\Entities\**" />
    <EmbeddedResource Remove="wwwroot\dist\Entities\**" />
    <None Remove="wwwroot\dist\Entities\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="TypeScript\src\app.ts" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="TypeScript\src\DTO\CreateItemsDto.ts" />
    <None Remove="TypeScript\src\DTO\UserDtos.ts" />
    <None Remove="TypeScript\src\Entities\Album.ts" />
    <None Remove="TypeScript\src\Entities\song.ts" />
    <None Remove="TypeScript\src\pages\createEditDeleteItemsForms\albumCreatorForms.ts" />
    <None Remove="TypeScript\src\pages\createEditDeleteItemsForms\formFieldsCreator.ts" />
    <None Remove="TypeScript\src\pages\createEditDeleteItemsForms\Shared\SelectInput.ts" />
    <None Remove="TypeScript\src\pages\createEditDeleteItemsForms\Shared\SharedFormsUtils.ts" />
    <None Remove="TypeScript\src\pages\createEditDeleteItemsForms\songCreatorForms.ts" />
    <None Remove="TypeScript\src\Utils\sharedSVgIcons.ts" />
    <None Remove="TypeScript\src\Utils\toast.ts" />
    <None Remove="TypeScript\src\pages\displayItemsSubpages\albumIdDetailsSubpage.ts" />
    <None Remove="TypeScript\src\pages\displayItemsSubpages\artistIdDetailsSubpage.ts" />
    <None Remove="TypeScript\src\pages\displayItemsSubpages\sharedDetailsSubpage.ts" />
    <None Remove="TypeScript\src\pages\displayItemsSubpages\songIdDetailsSubpage.ts" />
    <None Remove="TypeScript\src\pages\displayItemsSubpages\UserRegisterForm.ts" />
    <None Remove="TypeScript\src\pages\user\currentUser.ts" />
    <None Remove="TypeScript\src\pages\user\userButton.ts" />
    <None Remove="TypeScript\src\pages\user\UserPasswordChangeForm.ts" />
    <None Remove="TypeScript\src\pages\user\UserUpdateForm.ts" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\dist\" />
    <Folder Include="wwwroot\dist\DTO\" />
  </ItemGroup>

  <ItemGroup>
    <TypeScriptCompile Include="TypeScript\src\app.ts" />
    <TypeScriptCompile Include="TypeScript\src\DTO\CreateItemsDto.ts" />
    <TypeScriptCompile Include="TypeScript\src\DTO\UserDtos.ts" />
    <TypeScriptCompile Include="TypeScript\src\Entities\Album.ts" />
    <TypeScriptCompile Include="TypeScript\src\Entities\Artist.ts" />
    <TypeScriptCompile Include="TypeScript\src\Entities\Song.ts" />
    <TypeScriptCompile Include="TypeScript\src\pages\createEditDeleteItemsForms\albumCreatorForms.ts" />
    <TypeScriptCompile Include="TypeScript\src\pages\createEditDeleteItemsForms\artistCreatorForms.ts" />
    <TypeScriptCompile Include="TypeScript\src\pages\createEditDeleteItemsForms\Shared\formFieldsCreator.ts" />
    <TypeScriptCompile Include="TypeScript\src\pages\createEditDeleteItemsForms\Shared\ItemSharedForm.ts" />
    <TypeScriptCompile Include="TypeScript\src\pages\createEditDeleteItemsForms\Shared\SelectInput.ts" />
    <TypeScriptCompile Include="TypeScript\src\pages\createEditDeleteItemsForms\Shared\SharedFormsUtils.ts" />
    <TypeScriptCompile Include="TypeScript\src\pages\createEditDeleteItemsForms\songCreatorForms.ts" />
    <TypeScriptCompile Include="TypeScript\src\Utils\sharedSVgIcons.ts" />
    <TypeScriptCompile Include="TypeScript\src\Utils\toast.ts" />
    <TypeScriptCompile Include="TypeScript\src\pages\homePage.ts" />
    <TypeScriptCompile Include="TypeScript\src\pages\displayItemsSubpages\albumIdDetailsSubpage.ts" />
    <TypeScriptCompile Include="TypeScript\src\pages\displayItemsSubpages\artistIdDetailsSubpage.ts" />
    <TypeScriptCompile Include="TypeScript\src\pages\displayItemsSubpages\sharedDetailsSubpage.ts" />
    <TypeScriptCompile Include="TypeScript\src\pages\displayItemsSubpages\songIdDetailsSubpage.ts" />
    <TypeScriptCompile Include="TypeScript\src\pages\user\UserPasswordChangeForm.ts" />
    <TypeScriptCompile Include="TypeScript\src\pages\user\userRegisterForm.ts" />
    <TypeScriptCompile Include="TypeScript\src\pages\user\currentUser.ts" />
    <TypeScriptCompile Include="TypeScript\src\pages\user\userButton.ts" />
    <TypeScriptCompile Include="TypeScript\src\pages\user\userLoginForm.ts" />
    <TypeScriptCompile Include="TypeScript\src\pages\user\userButtonFunctions.ts" />
    <TypeScriptCompile Include="TypeScript\src\pages\user\userUpdateForm.ts" />
  </ItemGroup>

</Project>
